python_abi_tag:
 - cp27mu  # [linux]
 - cp27m   # [not linux]
 - cp35m   # [not (aarch64 or ppc64le)]
 - cp36m
 - cp37m
 - cp38

python_requirement:
 - 2.7.*
 - 3.5.*   # [not (aarch64 or ppc64le)]
 - 3.6.*
 - 3.7.*
 - 3.8.*

python_version:
 - 2.7
 - 3.5     # [not (aarch64 or ppc64le)]
 - 3.6
 - 3.7
 - 3.8

python_impl:
 - cpython
 - cpython  # [not (aarch64 or ppc64le)]
 - cpython
 - cpython
 - cpython

python:
 - "2.7"
c_compiler:
 - "*"
cxx_compiler:
 - "*"
vc:
 - "*"

zip_keys:
 -
   - python_abi_tag
   - python_version
   - python_requirement
   - python_impl
