python_abi_tag:
 - cp313
 - cp313t

python_impl_version:
 - 3.13
 - 3.13

python_version:
 - 3.13
 - 3.13

python_implementation:
 - cpython
 - cpython

zip_keys:
 -
   - python_abi_tag
   - python_version
   - python_impl_version
   - python_implementation
