python_abi_tag:
 - cp314
 - cp314t

python_impl_version:
 - 3.14
 - 3.14

python_version:
 - 3.14
 - 3.14

python_implementation:
 - cpython
 - cpython

zip_keys:
 -
   - python_abi_tag
   - python_version
   - python_impl_version
   - python_implementation
