{% set build_num = 0 %}

package:
  name: python_abi
  version: {{ python_version }}

build:
  number: {{ build_num }}
  string: {{ build_num }}_{{ python_abi_tag }}

requirements:
  run:
    - python {{ python_requirement }}
  run_constrained:
    - pypy <0a0

test:
  commands:
    - python --version

about:
  home: https://github.com/conda-forge/python_abi-feedstock
  summary: Metapackage to select python implementation
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
