{% set build_num = 0 %}

package:
  name: python_abi
  version: {{ python_version }}

outputs:
  - name: python_abi
    build:
      number: {{ build_num }}
      string: {{ build_num }}_{{ python_abi_tag }}
      track_features: pypy   # [python_impl == "pypy"]
      skip: True  # [python_impl == "pypy"]

    requirements:
      run:
        - python {{ python_requirement }}
      run_constrained:
        - pypy <0a0   # [python_impl == "cpython"]

  - name: cpython
    build:
      number: {{ build_num }}
      string: {{ build_num }}_{{ python_abi_tag }}
      skip: True   # [python_impl != "cpython"]
    requirements:
      run:
        - python_abi {{ python_version }} {{ build_num }}_{{ python_abi_tag }}

test:
  commands:
    - python --version

about:
  home: https://github.com/conda-forge/python_abi-feedstock
  summary: Metapackage to select python implementation
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
